<!-- JAVASCRIPT FILES -->
<script src="{{ asset('/js/jquery.min.js') }}"></script>
<script src="{{ asset('/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('/js/jquery.sticky.js') }}"></script>
<script src="{{ asset('/js/aos.js') }}"></script>
<script src="{{ asset('/js/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ asset('/js/magnific-popup-options.js') }}"></script>
<script src="{{ asset('/js/scrollspy.min.js') }}"></script>
<script src="{{ asset('/js/custom.js') }}"></script>